alias vi='vim'
alias ta='tmux attach-session -t'
alias ght='lpass show --notes "GitHub Token"'
alias lpcli='LPASS_DISABLE_PINENTRY=1 lpass login'
alias kclean='dpkg -l | egrep "linux\-(*image*|*headers*)\-[0-9]" | egrep -v "`uname -r | awk -F- '\''{print $1"-"$2}'\''`" | cut -d" " -f 3'
alias python='python3'
alias pythong='python3'
alias py='python3'
alias ac_cde='~/gitrepos/ac_patcher/ac_cde.sh'
