alias vi='vim'
alias ta='tmux attach-session -t'
alias ght='lpass show --notes "GitHub Token"'
alias lpcli='LPASS_DISABLE_PINENTRY=1 lpass login'
alias kclean='dpkg -l | egrep "linux\-(*image*|*headers*)\-[0-9]" | egrep -v "`uname -r | awk -F- '\''{print $1"-"$2}'\''`" | cut -d" " -f 3'
